### ISSUE TITLE
Adding an mac-arm64 self-hosted build

### ISSUE THREAD

**Issue by ghutchis** [grimme-lab/homebrew-qc#21]
I was looking at how the releases are built -- I'd be happy to offer my self-hosted GitHub runner for `arm64` bottles.

It looks like the main thing would be the `tests.yml` workflow, since the `publish.yml` simply adds the bottles to the release?

**Comment by marcelmbn** [comment]
If I understand you correctly, this offer should be irrelevant now that GitHub offers `arm64` runners, is that right, @ghutchis?
I've just just started updating the bottles to match higher versions of the software packages as well as more recent platforms. For `mctc-lib`, it looks like this:
https://github.com/grimme-lab/homebrew-qc/releases/tag/mctc-lib-0.3.2

**Comment by ghutchis** [comment]
Yes. The offer is irrelevant because there are `arm64` GitHub hosted runners.
